config/routes.rb
Rails.application.routes.draw do


get 'login' => 'sessions#new'
post 'login' =>'sessions#create'
get 'logout' => 'sessions#destroy'


#get "/books" => "books#index", as: 'books'
#get "/books/new" => "books#new", as: 'new_book'
#get "/books/:id" => "books#show", as: 'book'
#post "/books" => "books#create"
#get "/books/:id/edit" => "books#edit", as: 'edit_book'
#patch "/books/:id" => "books#update"
#delete "/books/:id" => "books#destroy"
#resources :books

resources :reservations do
  get 'page/:page', :action => :index, :on => :collection
end

resources :books do
  get 'page/:page', :action => :index, :on => :collection
end

resources :authors do
  get 'page/:page', :action => :index, :on => :collection
end

resources :users do
  get 'page/:page', :action => :index, :on => :collection
end

root 'books#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
validates :name, :dob, :nationality, :biography, :image_url,  presence: true
validates_length_of :biography, :minimum => 15

has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations

GENRES = ['Art','Cookbooks', 'Fantasy', 'History',  'Music', 'Psychology', 'Science Fiction']

validates :title, :pages, :isbn, :genre, :abstract, :image_cover_url, :published_on, :total_in_library, presence: true
validates :pages, numericality:{only_integer: true, greater_than_or_equal_to: 0}, unless: "pages.blank?"
validates_length_of :abstract, :minimum => 15
validates :genre, :inclusion => { :in => GENRES, :message => "Not a valid genre."}
validates :author_id, :presence => true

def self.search(query)
  joins(:author).where("title like? OR isbn like? OR genre like? or authors.name like ?", "%#{query}%" , "%#{query}%" , "%#{query}%", "%#{query}%")
end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

before_create :set_dates

private
  def set_dates
    self.reserved_on = DateTime.now.to_date
    self.due_on = DateTime.now.to_date + 10.days
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence:true, uniqueness:true
  has_many :reservations, dependent: :destroy
  has_many :books, through: :reservations
  has_secure_password

  def index
    @users = User.order(:name)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

before_filter :authorize

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def current_user
  @current_user || User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user

def authorize
  redirect_to '/login' unless current_user
end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authorize
  def index
@available_at = Time.now
    @authors = Author.order(:name)
  end

before_action :set_author, only: [ :show, :edit, :update, :destroy ]

  def show
    @author = Author.find(params[:id])
  end

def new
    @author = Author.new
  end

def create
  @author = Author.new(author_params)
  if @author.save
    #redirect_to @book
    redirect_to @author, notice: "#{@author.name} was created!"
    else
      render :new
    end
end

def edit
  #@author = Author.find(params[:id])
end

def update
  #@author = Author.find(params[:id])
  #@author.update(author_params)
  #redirect_to @author
  if @author.update(author_params)
    #redirect_to @author
    redirect_to @notice, notice: "#{@author.name} was updated!"
  else
      render :edit
  end
end

def destroy
  #@author = Author.find(params[:id])
  @author.destroy
  redirect_to books_url
end

private
def author_params
  params.require(:author).permit(:name, :dob, :nationality, :biography, :image_url)
end

def set_author
  @author = Author.find(params[:id])
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [ :show, :edit, :update, :destroy ]
  before_filter :authorize

  def index
    @available_at = Time.now
    if params[:search]
      @books = Book.search(params[:search]).page(params[:page])
    else
      @books = Book.order(:title).page(params[:page])
    end
  end

  def show
    #@book = Book.find(params[:id])
    @reservation = @book.reservations.where(["user_id = :user_id", { user_id: current_user.id}]).first
  end

  def new
    @book = Book.new
  end

def create
  @book = Book.new(book_params)
  if @book.save
    #redirect_to @book
    redirect_to @book, notice: "#{@book.title} was created!"
    else
      render :new
    end
end

def edit
  #@book = Book.find(params[:id])
end

def update
  #@book = Book.find(params[:id])
  #@book.update(book_params)
  #redirect_to @book
  if @book.update(book_params)
    #redirect_to @book
    redirect_to @book, notice: "#{@book.title} was updated!"
  else
      render :edit
  end
end

def destroy
  #@book = Book.find(params[:id])
  @book.destroy
  redirect_to books_url
end



private
def book_params
  params.require(:book).permit(:title, :author_id, :genre, :abstract, :pages, :image_cover_url, :published_on, :total_in_library, :isbn)
end

def set_book
  @book = Book.find(params[:id])
end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

before_filter :authorize

def index
@available_at = Time.now
isAdmin = params[:isAdmin]
  if current_user.admin == true && isAdmin == "1"
     @reservations = Reservation.where(["due_on < ?", DateTime.now.to_date]).order(:due_on)
   else
     #Show my reservations
      @reservations = Reservation.where(["user_id = ?", current_user.id])
   end
  end

before_action :set_reservation, only: [:show, :edit, :update, :destroy]

 def show
  @reservations = Reservation.where("user_id = ?", params[:current_user_id])
  end



  def new
    @reservation = Reservation.new
  end

def create
  @reservation = Reservation.new
  @reservation.book_id = params[:book_id]
  @reservation.user_id = current_user.id
  @reservation.save

  if @reservation.save
    redirect_to reservations_url , notice: "Reservation was created!"
  else
    redirect_to reservations_url, notice: "Reservation was NOT created!"
  end
end

def destroy
    # book_id = params[:book_id]
    # @reservation = reservations.where("user_id = :user_id and book_id = :book_id",
    #   {user_id: current_user.id, book_id: book_id})

  @reservation = Reservation.find(params[:id])

  if @reservation.destroy
    redirect_to reservations_url , notice: "Book was returned!"
  else
    redirect_to reservations_url, notice: "Book was NOT returned!"
  end
end


private
  def reservation_params
   params.require(:reservation).permit(:user_id, :book_id, :reserved_on, :due_on)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by_user_id(params[:user_id])
    if user && user.authenticate(params[:password_digest])
      #Log in use and redirect
      session[:user_id] = user.id
      $global_user_id = user.id
      redirect_to '/'
    else
      redirect_to '/login', notice: "Invalid user name/password."
    end
  end

  def destroy
    session[:user_id]=nil
    $global_user_id = nil
    redirect_to '/login', notice: "Successfully logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
@available_at = Time.now
    @users = User.order(:name)
  end

before_action :set_user, only: [ :show, :edit, :update, :destroy ]

def new
    @user = User.new
  end

  private
def book_params
  params.require(:user).permit(:name, :user_id, :password_digest, :admin)
end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_time(time)
    time.strftime("%B %d, %Y at %l:%M %p")
    end

def formatted_date(date)
    date.strftime("%B %d, %Y")
    end

    end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/authors/_form.html.erb
<% if current_user && current_user.admin == true %>

<%= form_for(@author) do |f| %>
<% render 'shared/validation_errors', object: @author %>
<%= f.label :name %> <%= f.text_field :name, autofocus: true, :size=> "30" %><br />

<%= f.label :dob %> <%= f.date_select :dob %><br />

<%= f.label :nationality %> <%= f.text_field :nationality %><br />

<%= f.label :biography %> <%= f.text_area :biography, size: "50x5" %><br />

<%= f.label :awards %> <%= f.text_field :awards, :size=> "80" %><br />

<%= f.label :image_url %> <%= f.text_field :image_url %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', authors_path %>
  </p>
<% end %>
<% else %>
<h3> Unauthorized </h3>
<p>You are not allowed to create/edit new authors.</p>
<% end %>

app/views/authors/edit.html.erb
 <% if current_user && current_user.admin == true %>

<h1>Editing Author <%= @author.name %></h1>
<%= render 'form' %>

<% else %>



<% end %>

app/views/authors/index.html.erb
  <% @authors.each do |author| %>

<div style="float:left; margin:0 1em .5em 0;">
<%= image_tag(author.image_url, height:"120") %>
<%= link_to(author.name, author) %>
</div>
 <div style="float:none; clear:both;"> </div>

<% end %>

app/views/authors/new.html.erb
<h1>Create a New Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<% content_for :name, @author.name %>


<article class="author">
  <header>
    <h2><%= @author.name %></h2>
  </header>

<div style="float:left; margin:0 1em .5em 0;"><%= image_tag(@author.image_url, height:"240") %></div>
<p><%= @author.biography %></p>

<h3>Details</h3>
  <p><label>Date of birth:</label> <%= @author.dob %></p>
  <p><label>Nationality:</label> <%= @author.nationality %></p>
  <p><label>Awards:</label> <%= @author.awards %></p>

<h3>Publications</h3>
<% @author.books.each do |book| %>
<div style="float:left; margin:0 1em .5em 0;">
<%= link_to(image_tag(book.image_cover_url, height:"120"), book) %>
</div>
<p><%= link_to(book.title, book) %></p>

 <div style="float:none; clear:both;"> </div>
<% end %>
 <div style="float:none; clear:both;"> </div>
</article>

<%= link_to 'All Authors', authors_path %>
<% if current_user && current_user.admin == true %>

 | <%= link_to 'Edit', edit_author_path(@author) %>
 <% if @author.books.count == 0 %>
<%= button_to 'Delete', @author,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<% if current_user && current_user.admin == true %>
<%= form_for(@book) do |f| %>
  <% render 'shared/validation_errors', object: @book %>
  <%= f.label :title %> <%= f.text_field :title, autofocus: true , :size=> "50" %><br />
  <%= f.label :author %> <%= collection_select(:book, :author_id, Author.all, :id, :name, {}, { :multiple => false}) %><br />


  <%= f.label :isbn %> <%= f.text_field :isbn %><br />

<%= f.label :abstract %> <%= f.text_area :abstract, size: "50x5" %><br />


   <%= f.label :genre %> <%= f.select :genre, Book::GENRES, {prompt: "Pick One"} %><br />

  <%= f.label :pages %> <%= f.text_field :pages %><br />

   <%= f.label :total_in_library %> <%= f.text_field :total_in_library %><br />

   <%= f.label :published_on %> <%= f.date_select :published_on %><br />

   <%= f.label :image_cover_url %> <%= f.text_field :image_cover_url, :size=> "70" %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', books_path %>
  </p>
<% end %>
<% else %>
<h3> Unauthorized </h3>
<p>You are not allowed to create/edit new authors.</p>
<% end %>

app/views/books/_resForm.html.erb
<%= form_for(@book) do |f| %>
<%= hidden_field_tag(:user_id, value = current_user.id ) %>
<%= hidden_field_tag(:book_id, value = @book.id ) %>
<%= button_to 'reservations', @reservation %>
<% end %>

app/views/books/_search.html.erb
<div class="right">
<%= form_tag(books_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search on isbn, title, genre, or author.", :size=> "30"  %>
<button type="submit">Search</button>
<% end %>
<%= yield %>
</div>
<div class="clearAll"></div>

app/views/books/edit.html.erb
<%= render 'search' %>
<h1>Editing Book <%= @book.title %></h1>

<%= render 'form' %>

app/views/books/index.html.erb
<%= render 'search' %>


<p>Available as <%= formatted_time(@available_at) %></p>
<%= page_entries_info @books %>
<div style="float:none; clear:both;"> </div>

<% @books.each do |book| %>
<div>
  <div style="float:left; margin:1em 1em .5em 0;">
    <%= image_tag(book.image_cover_url, height:"120") %>
</div>
   <div style="float:left; margin:1em 1em .5em 0;"><%= link_to(book.title, book) %> by <%= book.author.name %></div>

</div>
 <div style="float:none; clear:both;"> </div>
 <% end %><%= paginate @books %>

app/views/books/new.html.erb
<%= render 'search' %>
<h1>Create a New Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<%= render 'search' %>

<% content_for :title, @book.title %>


<article class="book">
  <header>
    <h2><%= @book.title %> </h2>
  </header>

<div style="float:left; margin:0 1em .5em 0;"><%= image_tag(@book.image_cover_url, height:"240") %></div>
<p><label>ISBN:</label> <%= @book.isbn %></p>
  <p><label>Author:</label> <%= @book.author.name %></p>
  <p><label>Genre:</label> <%= @book.genre %></p>
  <p><label>Pages:</label> <%= number_with_delimiter(@book.pages) %></p>
  <p><label>Date Published:</label> <%= @book.published_on %></p>
  <p><label>Abstract:</label> <%= @book.abstract %></p>
  <p><label>Number Available to Reserve:</label> <%= @book.total_in_library %></p>

  <p>
    <% if @book.total_in_library > @book.reservations.count %>
      <% if @book.reservations.where(["user_id = :user_id", { user_id: current_user.id}]).count == 0 %>
        <%= button_to "Reserve This Book", {:controller => "reservations", :action =>"create", :book_id => @book.id }, :method => :post %>
      <% else %>
        You have already reserved this book.
      <% end %>

    <% else %>
      All of these books are checked out.
    <% end %>
  </p>

<% if @reservation %>
 <p>
    <%= button_to "Return This Book", reservation_path(@reservation), :method => :delete %>
  </p>
<% end %>

 <div style="float:none; clear:both;"> </div>
</article>

<br>



<%= link_to 'All Books', books_path %>
<% if current_user && current_user.admin == true %>| <%= link_to 'Edit', edit_book_path(@book) %>
<%= button_to 'Delete', @book,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
               <% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
  <h1><%= link_to('Awesome Books', root_path) %></h1>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <% if current_user %>
  <div class="panel panel-primary">


    <div class="panel-heading">
      <h3 class="panel-title">Navigation</h3>
    </div>
    <div class="panel-body">


      <p>
        <%= link_to 'All Books', books_path %>
      </p>
      <p>
        <%= link_to 'All Authors', authors_path %>
      </p>

      <% if current_user && current_user.admin == true %>
      <p>
        <%= link_to 'Create Author', new_author_path %>
      </p>
      <p>
        <%= link_to 'Create Book', new_book_path %>
      </p>
       <p>
        <%= link_to 'All Users', users_path %>
      </p>

       <% end %>


      <% if current_user && current_user.admin == true %>
      <p>
        <%= link_to 'Overdue Reservations', reservations_path(isAdmin: "1")  %>
       </p>
       <% end %>

       <p>
        <%= link_to 'My Reservations', reservations_path  %>
       </p>



<%= link_to "Logout", '/logout' %>


    </div>

  </div>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome Books <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/reservations/index.html.erb
<h3>Reservations</h3>

<p>


<% @reservations.each do |reservation| %>






<article class="book">
<div style="float:left; margin:0 1em .5em 0;"><%= image_tag(reservation.book.image_cover_url, height:"240") %></div>
<% date_diff = (reservation.due_on.to_date - DateTime.now.to_date).to_i  %>
<h4><%= reservation.book.title %></h4>


  <p>Reserved by: <%= reservation.user.name %> </p>

  <p> Reserved on: <%= reservation.reserved_on %> </p>

  <p>Due on <%= reservation.due_on %></p>

  <% if date_diff < 0 %>
  <p><span class="overdue">Overdue</span></p>
  <% end %>

<% if reservation.user_id == current_user.id %>
<p>
    <%= button_to "Return This Book", reservation_path(reservation), :method => :delete %>
  </p>
<% end %>

 <div style="float:none; clear:both;"> </div>


</article>

  <% end %>

</p>

app/views/reservations/new.html.erb
Reservation Created

app/views/reservations/show.html.erb
<h3>Reservations</h3>

<p><%= current_user.id %></p>

<% @reservations.each do |reservation| %>


ID <% @reservation.id %><br>

USER ID <% @reservation.user_id %><br>

Book ID <% @reservation.book_id %><br>

Reserved On <% @reservation.reserved_on %><br>

<br>

<% end %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h2>Listing of All Users</h2>

<div class="container">
<table class="user">
  <thead>
    <tr >
      <th class="user">Name</th>
      <th class="user">User ID</th>
      <th class="user">Is Admin</th>
      <th class="user">Date Created</th>
      <th class="user">Date Updated</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="user"><%= user.name %></td>
        <td class="user"><%= user.user_id %></td>
        <td class="user"><%= user.admin %></td>
        <td class="user"><%= formatted_date(user.created_at) %></td>
        <td class="user"><%= formatted_date(user.updated_at) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>